### ISSUE TITLE
[Tracking Issue] Add document strings to public methods

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DecisionTree.jl#215]
Here's what I think are intended to be public, ranked in rough order of priority:

- [ ] `build_forest` #214 @ablaom
- [ ] `apply_forest`
- [ ] `apply_forest_proba`
- [ ] `build_tree`
- [ ] `print_tree`
- [ ] `apply_tree`
- [ ] `apply_tree_proba`
- [ ] `build_adaboost_stumps`
- [ ] `apply_adaboost_stumps`
- [ ] `apply_adaboost_stumps_proba`
- [ ] `nfoldCV_forest`
- [ ] `nfoldCV_tree`
- [ ] `nfoldCV_stumps`
- [ ] `load_data`
- [ ] `DecisionTree.confusion_matrix`
- [ ] `DecisionTree.util.gini`
- [ ] `DecisionTree.util.entropy`
- [ ] `DecisionTree.util.zero_one`

Already documented are:

- `impurity_importance`
- `split_importance`
- `permutation_importance`

Any help here appreciated. Take a look at #214 to get an idea of existing format.
